### ISSUE TITLE
Toasts overlapping notch in notched android phone

### ISSUE THREAD

**Issue by Draika** [kotcrab/vis-ui#302]
I'm experimenting with full immersion support using a notched Android phone. The standard configuration of ToastManager puts Toasts on the top right corner, which overlaps the notch on the phone, so I would like to introduce some y axis padding.

I can of course change the alignment, but the rest of the screen in my project are already dedicated for user interaction and controls.

I can call setScreenPadding() to move all the toasts away from the notch on the y axis but they also move away from the x axis as well which looks weird. I can't see an easy way to adjust just the y axis without subclassing. Can we change screenPadding in ToastManager to screenPaddingX and screenPaddingY and adjust padding behaviour accordingly?

**Comment by Draika** [comment]
**Hack solution**
I thought subclassing could solve the problem but I came across coupling with the Toast class with the built in ToastManager class. Crazy how draconic Java can be due to API limitations. 

My solution involves reflection using libgdx reflection classes in com.badlogic.gdx.utils.reflect

`
public void updateToastPositions() {
		try {
			Field declaredField = ClassReflection.getDeclaredField(toastManager.getClass(), "toasts");
			declaredField.setAccessible(true);
			@SuppressWarnings("unchecked")
			Array<Toast> fieldValue = (Array<Toast>) Reflection.getFieldValue(declaredField, toastManager);
			float y = stage.getHeight()-[Insert notch padding here, i used Gdx.graphics.getHeight()/12];
			for (Toast toast : fieldValue) {
					Table table = toast.getMainTable();
					table.setPosition(
							stage.getWidth() - table.getWidth() - 20,
							y - table.getHeight());

					y += (table.getHeight() + toastManager.getMessagePadding()) * -1;
			}
		} catch (ReflectionException e) {
			e.printStackTrace();
		}
	}
`

**Comment by kotcrab** [comment]
All done, `ToastManager#getScreenPadding()` had to be deprecated but it shouldn't case any breaking changes. More details can be found in `CHANGES.md`. Thanks for reporting.

> I thought subclassing could solve the problem but I came across coupling with the Toast class with the built in ToastManager class. Crazy how draconic Java can be due to API limitations.

Well, those classes aren't designed for extending so you will end up with hacks.
