### ISSUE TITLE
Should FileChooser work on HTML?

### ISSUE THREAD

**Issue by calanti** [kotcrab/vis-ui#304]
I'm pretty new to GWT/HTML, but I am trying to compile my project using html:superDev and it fails, errors show this;

      [ERROR] Line 20: No source code is available for type com.kotcrab.vis.ui.widget.file.FileChooser; did you forget to inherit a required module?
      [ERROR] Line 22: No source code is available for type com.kotcrab.vis.ui.widget.file.FileChooser.Mode; did you forget to inherit a required module?
      [ERROR] Line 23: No source code is available for type com.kotcrab.vis.ui.widget.file.FileChooser.SelectionMode; did you forget to inherit a required module?
      [ERROR] Line 28: No source code is available for type com.kotcrab.vis.ui.widget.file.StreamingFileChooserListener; did you forget to inherit a required module?
      [ERROR] Line 54: No source code is available for type com.kotcrab.vis.ui.widget.file.FileChooserListener; did you forget to inherit a required module?

Is the FileChooser actually compatible with HTML or do I need to find another way to open files in web?

Awesome project by the way.

**Comment by kotcrab** [comment]
It's not compatible as stated in the [wiki](
https://github.com/kotcrab/vis-ui/wiki/File-chooser) and [Javadocs](https://github.com/kotcrab/vis-ui/blob/master/ui/src/main/java/com/kotcrab/vis/ui/widget/file/FileChooser.java#L70).

> Chooser is platform dependent and can be only used on desktop.

You also might have forgotten to add GWT inherits. See main repo page for details.
```xml
<inherits name='com.kotcrab.vis.vis-ui' />
```

**Comment by calanti** [comment]
Do you know if there is any possible way to open or save local files in HTML?

**Comment by kotcrab** [comment]
Sorry, I don't really know GWT.
