### ISSUE TITLE
ArrayIndexOutOfBounds exception when selecting something in a VisTextArea

### ISSUE THREAD

**Issue by Teekeks** [kotcrab/vis-ui#307]
Java version used: JavaSE 11
libGDX version used: 1.9.9 with lwjgl3 backend
visUI version used: 1.4.2

Ways to reproduce: 

- have multible lines of text in a VisTextArea.
- **make sure that the first line is empty (just a linebreak)**
- start selection in line 2 by holding left mouse button
- click drag the selection up to 0,0 (as you would do if you want to select everything before the point you started the selection on)

The Application crashes with the following Stacktrace: https://pastebin.com/BTiDiKeS

**Comment by kotcrab** [comment]
Fixed, thanks for reporting
