### ISSUE TITLE
How to build the demo for the browser..?

### ISSUE THREAD

**Issue by wordlessly** [kotcrab/vis-ui#312]
Hi,

you offer a browser demo of the UI showcase: https://vis.kotcrab.com/demo/ui

Can you please tell me where to find the build file to repeat this?

Cheers!

**Comment by kotcrab** [comment]
Test source code is available [here](https://github.com/kotcrab/vis-ui/tree/master/ui/src/test/java/com/kotcrab/vis/ui/test/manual). However to build this as GWT you will need to create new libGDX project and add the relevant files. There's no example of this in VisUI.

**Comment by wordlessly** [comment]
I know the test source code since TestLauncher is also used to establish the desktop:run. Can't you just up the libGDX/GWT/Gradle setup somewhere since you already have it to produce the demo?

**Comment by kotcrab** [comment]
I have some ancient version so there's no point in uploading those. I always recreated the project for the demo to use latest lib versions. The setup isn't that complicated.
