### ISSUE TITLE
VisScrollPane's lower right corner is missing when both scroll bars visible

### ISSUE THREAD

**Issue by azurvii** [kotcrab/vis-ui#314]
When `VisScrollPane` is used and both x and y scroll bars are visible, the lower right corner is missing. It looks like the following screenshot:

![missing-scrollbar-corner](https://user-images.githubusercontent.com/3889447/66397276-096b9d00-ea0e-11e9-96b4-78263622197b.png)

Looking at [`ScrollPane`](https://github.com/libgdx/libgdx/blob/73f7b1d6665ae2b41c7a5c538ee259bded39b01a/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java#L620), it seems the `corner` should be the key to get the area covered.
Looking at [`uiskin.json`](https://github.com/kotcrab/vis-ui/blob/a79ace7103c96b97317e596f0729996d7a9cccb1/ui/src/main/resources/com/kotcrab/vis/ui/skin/x1/uiskin.json#L41), it seems `corner` is not defined.
I guess that's the cause.

**Comment by kotcrab** [comment]
Fixed, thanks for reporting. FYI the `uiskin.json` is generated from [USL](https://github.com/kotcrab/vis-ui/tree/master/usl/styles).
