### ISSUE TITLE
BusyBar grows but does not shrink

### ISSUE THREAD

**Issue by azurvii** [kotcrab/vis-ui#316]
* Place `BusyBar` in a `Table`, which fills the window.
* Resize the window to observe the bar's behavior.

It grows when the window is sized bigger, but it does not shrink when the window is sized smaller.
[Code](https://github.com/kotcrab/vis-ui/blob/df3b389c00f9343124dbe180631b3c9d14ae7a91/ui/src/main/java/com/kotcrab/vis/ui/widget/BusyBar.java) suggests that the height is constant. So it seems to be only about how the width is determined when the layout changes.

**Comment by kotcrab** [comment]
A possible fix is overriding `getPrefWidth` and returning some constant value.

**Comment by kotcrab** [comment]
Fixed, thanks!
