### ISSUE TITLE
ToolTips still crashing with 1.4.5-SNAPSHOT

### ISSUE THREAD

**Issue by Crigges** [kotcrab/vis-ui#320]
Same problem as #291
My gradle.build file: https://pastebin.com/KnzhpNPt

When I change the gdx version to 1.9.8 it's working.

**Comment by kotcrab** [comment]
I have trouble reproducing this. Please provide your full example and stack trace, also can you try with VisUI 1.4.4 and libGDX 1.9.10?

**Comment by Crigges** [comment]
Testet with 1.4.4 doesn't work either.
Full Stack Trace:
https://pastebin.com/8vxZ0804
MVCE:
https://pastebin.com/SM4z9Qep

**Comment by Crigges** [comment]
Stupid me. 
Since you couldn't reproduce I was pretty sure gradle was downloading the wrong version. The project is pretty old, and as it seems, I had `visuiVersion` already definied later in the ext block of my gradle.build file:
```
visuiVersion = '1.4.5-SNAPSHOT'
gdxVersion = '1.9.10'
roboVMVersion = '2.1.0'
box2DLightsVersion = '1.4'
ashleyVersion = '1.7.0'
aiVersion = '1.8.0'
visuiVersion = '1.2.4'
```

**Comment by kotcrab** [comment]
It happens, glad you got it working!
