### ISSUE TITLE
Create a Website for this Repo

### ISSUE THREAD

**Issue by xdvrx1** [kotcrab/vis-ui#334]
Hi there. 

Is there a website for this repo? 

Because if you don't have, well, this repo can simply be turned into a website right away. Others will discover this project in that website.

Steps:
1. Go to Settings and look for `GitHub Pages`, scroll down. That's almost at the bottom.

2. You will see there: `Branch:none`, so you should change that to `master` because you have a `README.md` file in the master repo. This will be your page. Click `Save` first.

3. Then click `Choose a theme`, you select a predefined theme of your site.

4. Visit your site now! The URL will be `https://kotcrab.github.io/vis-ui`. 

If you were amazed by that, simply read the documentation about GitHub Pages.

**Comment by kotcrab** [comment]
There is a website at https://github.com/kotcrab/vis-ui/blob/master/README.md :) Nothing else is really necessary

**Comment by xdvrx1** [comment]
That's not a website. You simply look at the domain. It's different. Maybe you don't fully understand the difference between the two. Why do you think GitHub created GitHub Pages? It's different from simply having `README.md` in your GitHub Repo.

**Comment by kotcrab** [comment]
I'm not here to argue about the definition of a website. This project is not actively developed, it doesn't need anything else than this README page. Adding Github pages adds one more component to maintain.

**Comment by xdvrx1** [comment]
I am just suggesting also, well maybe you can try GitHub Pages maybe sometime. It's not that hard to be maintained.
