### ISSUE TITLE
Preview in BasicColorPicker should be optional

### ISSUE THREAD

**Issue by cypherdare** [kotcrab/vis-ui#340]
As-is, the BasicColorPicker is designed for use in a dialog or pop-up. If you just want to use it persistently on a screen and see immediate results, [like I'm doing here](https://cyphercove.github.io/ColorInterpolationComparison/), then you want to hide the preview.

If you're open to it, I can make a PR.

**Comment by kotcrab** [comment]
I agree, you can make PR for it. Should be pretty easy.
