### ISSUE TITLE
VisUI Tixel Skin, where'd it go?

### ISSUE THREAD

**Issue by unenergizer** [kotcrab/vis-ui#354]
I can't seem to find the Tixel skin for VisUI. I've been searching for it but can't find it on google or referenced in the documents here. Was it deprecated?

**Comment by kotcrab** [comment]
I think it always was in the contrib repo https://github.com/kotcrab/vis-ui-contrib/tree/master/skins/tixel just keep in mind it wasn't updated for a long time.

**Comment by unenergizer** [comment]
If I upgrade my version of VisUI, should I drop the tixel skin and just modify the default one that comes with this library?

**Comment by kotcrab** [comment]
If you want to keep using tixel skin it should be fairly easy to update. It's mostly just USL overrides https://github.com/kotcrab/vis-ui-contrib/blob/master/skins/tixel/tixel.usl

If not using the default skin is the easiest. 

> EDIT: Sorry for contacting you here, I didn't see a way to email or message you other than on here.

It's okay.
