### ISSUE TITLE
Tree node is removed but the container remains

### ISSUE THREAD

**Issue by ronjunevaldoz** [kotcrab/vis-ui#361]
Tree node is removed but the container remains. After removing the node using `actor.remove()` the node container remains

- Initial load
  ![image](https://user-images.githubusercontent.com/4947998/117102248-84439800-adaa-11eb-93bb-30a87c04d97d.png)
- After removal
  ![image](https://user-images.githubusercontent.com/4947998/117102212-6ece6e00-adaa-11eb-8ebe-750d3865b5f5.png)

**Comment by czyzby** [comment]
`VisTree` extends the default LibGDX `Tree` with `Focusable` support, but node management remains unchanged. It's likely that it's a LibGDX bug. @ronjunevaldoz, would you be able to verify that a similar bug occurs with the default widget?

**Comment by ronjunevaldoz** [comment]
> `VisTree` extends the default LibGDX `Tree` with `Focusable` support, but node management remains unchanged. It's likely that it's a LibGDX bug. @ronjunevaldoz, would you be able to verify that a similar bug occurs with the default widget?

I tried using the default Tree, the bug still occurs.

**Comment by czyzby** [comment]
Since `VisTree` is a very basic extension of the official `Tree`, I think this bug should be fixed at its source. Please create a bug report in the [LibGDX](https://github.com/libgdx/libgdx) repository.
