### ISSUE TITLE
Enhance VisWindow

### ISSUE THREAD

**Issue by Osiris-Team** [kotcrab/vis-ui#371]
- [ ] Add functionality to drag and drop a VisWindow out of the window.
- [ ] Make it easier to customize the window title.

**Comment by czyzby** [comment]
> Add functionality to drag and drop a VisWindow out of the window.

VisUI deals with widgets that are rendered via the `Stage` API. True multi-window setup implementation is out of scope of the library, but I believe it's possible to implement with the new LWJGL desktop backend.

> Make it easier to customize the window title.

`VisWindow` extends libGDX `Window`, reusing most of its APIs. Title handing is done by the original libGDX implementation. You can use `getTitleLabel` and `getTitleTable` if you want to have more control over how the layout looks and what is displayed. If that's not enough, I encourage you to make a PR or create an issue in the official libGDX repository.

**Comment by Osiris-Team** [comment]
Thanks for the clarification!
