### ISSUE TITLE
TabbedPane clicking a tab makes it invisible

### ISSUE THREAD

**Issue by amoustafa18** [kotcrab/vis-ui#380]
![Screen Recording 2022-12-22 at 3 53 37 PM](https://user-images.githubusercontent.com/21189634/209224065-949274b7-a548-4783-ae49-fd8bb231a597.gif)

When I click a tab in a TabbedPane, the tab goes invisible (in response to touchUp). I am certain the tab is not closing, the TabbedPane still has the tabs in its internal list. On the latest versions (libGDX 1.11.0, visUI 1.5.2-SNAPSHOT) and running on macOS. I don't have any special code for handling mouse events, so this seems to be out-of-the-box behavior.

**Comment by czyzby** [comment]
Could you post a minimal example of a project that reproduces the issue?

**Comment by amoustafa18** [comment]
While stripping out some of my extra code to give a minimal example, I ended up fixing the issue on my end. I realized I was missing a call to super.act in my override of act(). Sorry about this

**Comment by czyzby** [comment]
No worries, glad you figured it out.
